apiVersion: v3
name: etri-arduino-temperature
manufacturer: Arduino
model: Arduino temperature sensor
labels:
- arduino
- serial
- physical-sensor
- edgeai
description: Read-only temperature channel on the shared Arduino serial connection
deviceResources:
- description: Raw temperature sensor value
  name: temperature_raw
  isHidden: false
  properties:
    valueType: Int32
    readWrite: R
    units: raw
deviceCommands:
- name: temperature
  readWrite: R
  resourceOperations:
  - deviceResource: temperature_raw
