apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgex-edge
resources:
- workload.yaml
configMapGenerator:
- name: device-serial-jetson-config
  files:
  - configuration.yaml
  - etri-arduino-temperature.yaml
  - etri-arduino-light.yaml
  - etri-arduino-magnetic.yaml
  - etri-arduino-acceleration-x.yaml
  - etri-arduino-acceleration-y.yaml
  - etri-arduino-acceleration-z.yaml
  - devices.yaml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: edgeai
    app.kubernetes.io/managed-by: edgeai-repo
