apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: device-serial-jetson
    app.kubernetes.io/part-of: edgeai
    app.kubernetes.io/managed-by: edgeai-repo
  name: device-serial-jetson
  namespace: edgex-edge
spec:
  ports:
  - name: http
    port: 59910
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: device-serial-jetson
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: device-serial-jetson
    app.kubernetes.io/part-of: edgeai
    app.kubernetes.io/managed-by: edgeai-repo
  name: device-serial-jetson
  namespace: edgex-edge
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: device-serial-jetson
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: device-serial-jetson
        app.kubernetes.io/part-of: edgeai
        app.kubernetes.io/managed-by: edgeai-repo
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - -cp=keeper.http://edgex-core-keeper.edgex-system.svc.cluster.local:59890
        - -cd=/res
        env:
        - name: EDGEX_SECURITY_SECRET_STORE
          value: 'false'
        - name: SERVICE_HOST
          value: device-serial-jetson.edgex-edge.svc.cluster.local
        - name: SERVICE_SERVERBINDADDR
          value: 0.0.0.0
        - name: CLIENTS_CORE_METADATA_HOST
          value: edgex-core-metadata.edgex-system.svc.cluster.local
        - name: MESSAGEBUS_HOST
          value: edgex-messagebus.edgex-system.svc.cluster.local
        image: 192.168.0.56:5000/edgex-device-serial@sha256:4855c4a949a3531ab947ec4bafd9aae6d6f3ed374e6b8cb82706d0b54ebfce63
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v3/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: device-serial-jetson
        ports:
        - containerPort: 59910
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v3/ping
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /api/v3/ping
            port: http
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /res
          name: service-config
          readOnly: true
        - mountPath: /dev/edgeai
          name: arduino-serial
          readOnly: true
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: etri-dev0001-jetorn
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 20
      volumes:
      - configMap:
          name: device-serial-jetson-config
          items:
          - key: configuration.yaml
            path: configuration.yaml
          - key: etri-arduino-temperature.yaml
            path: profiles/etri-arduino-temperature.yaml
          - key: etri-arduino-light.yaml
            path: profiles/etri-arduino-light.yaml
          - key: etri-arduino-magnetic.yaml
            path: profiles/etri-arduino-magnetic.yaml
          - key: etri-arduino-acceleration-x.yaml
            path: profiles/etri-arduino-acceleration-x.yaml
          - key: etri-arduino-acceleration-y.yaml
            path: profiles/etri-arduino-acceleration-y.yaml
          - key: etri-arduino-acceleration-z.yaml
            path: profiles/etri-arduino-acceleration-z.yaml
          - key: devices.yaml
            path: devices/devices.yaml
        name: service-config
      - hostPath:
          path: /run/edgeai/devices
          type: Directory
        name: arduino-serial
      - emptyDir: {}
        name: tmp
