apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgex-edge
resources:
- workload.yaml
configMapGenerator:
- name: device-sensehat-raspi-config
  files:
  - configuration.yaml
  - etri-sensehat-temperature.yaml
  - etri-sensehat-humidity.yaml
  - etri-sensehat-pressure.yaml
  - etri-sensehat-compass.yaml
  - etri-sensehat-orientation.yaml
  - etri-sensehat-gyroscope.yaml
  - devices.yaml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: edgeai
    app.kubernetes.io/managed-by: edgeai-repo
