/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 플랫폼 정보와 구현된 기능 조회
         * @description 서버 이름·버전·현재 개발 단계와 실제 구현된 profiles/devices/nodes 기능을 반환합니다. 인증이 필요합니다.
         */
        get: operations["getPlatform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버와 PostgreSQL의 요청 처리 준비 상태 확인
         * @description 애플리케이션과 PostgreSQL이 함께 준비되어 있으면 200/UP을 반환합니다. DB 연결 장애 등으로 요청을 처리할 수 없으면 503/DOWN을 반환합니다. Kubernetes readiness probe가 사용하며 인증은 필요하지 않습니다. 내부 접속 정보는 응답하지 않습니다.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 쓰기 요청에 사용할 CSRF 토큰 발급
         * @description Basic 인증 후 호출하면 token과 EDGEAI_SESSION 세션 쿠키를 받습니다. 직접 POST를 호출하는 클라이언트는 같은 쿠키와 X-CSRF-TOKEN 헤더, Basic 인증을 함께 보내야 합니다. 토큰은 로그인용 액세스 토큰이 아닙니다. Swagger에서는 자동 처리하므로 수동 입력할 필요가 없습니다.
         */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        /**
         * 종류별 프로필 버전 목록 조회
         * @description 선택한 종류의 발행 버전을 페이지로 조회합니다. key를 지정하면 해당 키와 정확히 일치하는 버전만 반환합니다.
         *
         *     key와 version의 문자열 오름차순입니다. 따라서 1.0.0 → 10.0.0 → 2.0.0 순서일 수 있으며 최신 버전을 계산하는 API가 아닙니다. 다음 페이지는 nextOffset을 offset으로 전달하며, null이면 마지막입니다.
         */
        get: operations["listProfiles"];
        put?: never;
        /**
         * 프로필 새 버전 등록
         * @description DEVICE(장치 규격), SERVICE(서비스 규격), VD(가상 장치 규격) 중 종류를 선택해 JSON 문서를 발행합니다.
         *
         *     새 key/version은 201, 같은 종류·key·version에 같은 내용을 재전송하면 기존 id와 생성 시각을 유지한 200을 반환합니다. 같은 버전에 다른 내용을 보내면 409이며 version을 올려 등록해야 합니다. 발행 후 수정·삭제할 수 없습니다.
         *
         *     Basic 인증·세션 쿠키·CSRF 토큰이 필요합니다. 요청은 UTF-8 기준 64 KiB 이하, spec은 비어 있지 않은 JSON 객체여야 합니다. 최대 중첩 깊이는 32이며 중복 JSON 키와 key/version/spec 이외의 최상위 필드는 거절합니다. 아래 규격은 입력 예시이며 실제 장치/런타임 호환성 검증은 후속 개발 범위입니다.
         */
        post: operations["publishProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{kind}/{key}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
                kind: components["parameters"]["Kind"];
                /** @description 조회할 프로필의 고유 키입니다. */
                key: components["schemas"]["ProfileKey"];
                /** @description 조회할 정확한 발행 버전입니다. 예: 1.0.0 */
                version: components["schemas"]["Version"];
            };
            cookie?: never;
        };
        /**
         * 프로필의 특정 버전 상세 조회
         * @description kind·key·version으로 발행 버전 하나를 정확히 조회합니다. 저장된 spec, 내용 식별용 SHA-256 digest, 최초 생성 시각을 반환합니다. 이전 버전 내용을 확인하거나 후속 장치/실행 기능에서 참조할 버전을 선택할 때 사용합니다. 해당 버전이 없으면 404를 반환합니다.
         */
        get: operations["getProfileVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 프로세스 생존 상태 확인
         * @description Spring Boot 프로세스가 정상인지 확인합니다. DB 상태는 검사하지 않으므로 DB 장애만으로 서버를 반복 재시작하지 않습니다. Kubernetes liveness/startup probe에 사용하며 인증이 필요하지 않습니다.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장치 목록과 연결 상태 조회
         * @description key 문자열 오름차순으로 조회합니다. 해제된 장치도 이력 조회를 위해 포함합니다. 활성 세션의 최근 보고가 60초보다 오래되면 STALE이며, 보고 전에는 UNKNOWN입니다.
         */
        get: operations["listDevices"];
        put?: never;
        /**
         * 물리 장치 등록
         * @description DEVICE Profile의 발행 UUID를 참조해 장치를 등록합니다. 같은 key와 동일 생성 입력은 200, 새로운 장치는 201, 다른 생성 입력은 409입니다. LIVE/REPLAY/SYNTHETIC으로 데이터 출처를 구분합니다. 등록만으로 실제 연결을 ONLINE으로 표시하지 않습니다. 요청 최대 16 KiB.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        /**
         * 장치 상세·연결 이력·최근 관측 조회
         * @description 장치와 최근 연결/세션/관측 각각 최대 20개를 반환합니다. 시간은 UTC이며 신선도는 서버 수신 시각으로 판단합니다. raw 스트림은 저장하지 않습니다.
         */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /**
         * 장치 해제 및 세션 종료
         * @description 장치를 RELEASED로 표시하고 활성 attachment/session을 닫습니다. 과거 이력을 보존하며 반복 해제는 같은 상태를 반환합니다. 해제 후 연결·세션·관측·수정 요청은 409입니다.
         */
        delete: operations["releaseDevice"];
        options?: never;
        head?: never;
        /**
         * 장치 표시 이름 수정
         * @description 상세 조회에서 받은 revision과 새 displayName을 전송합니다. 동시에 수정되어 revision이 바뀌면 409입니다. Profile 참조·key·sourceMode는 변경하지 않습니다.
         */
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/attachments/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 장치를 관측된 실행 노드에 연결
         * @description 최근 60초 안에 실제 관측된 Ready Node와 port를 연결합니다. 기존 활성 연결은 닫고 새 이력을 만들며 동일 node/port 재전송은 이력을 추가하지 않습니다. 장치당 활성 연결은 하나입니다.
         */
        put: operations["attachDevice"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 재접속·재부팅 세션 시작
         * @description bootId는 재부팅/재접속마다 새 UUID입니다. 현재 bootId 재전송은 200, 새 bootId는 기존 세션을 닫고 epoch를 올려 201입니다. 닫힌 bootId는 재사용할 수 없습니다. 이전 세션의 관측은 차단됩니다.
         */
        post: operations["openDeviceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장치 상태·작은 관측 데이터 보고
         * @description 현재 sessionId, 증가하는 sequence, observedAt, ONLINE/OFFLINE, attributes를 보냅니다. 동일 sequence/내용 재전송은 200, 내용 변경·역순·이전 세션은 409입니다. observedAt은 서버보다 최대 30초 미래·24시간 과거를 허용합니다. 요청 최대 16 KiB이며 raw stream/대형 파일은 대상이 아닙니다.
         */
        post: operations["reportDeviceObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관측된 Kubernetes 실행 노드 목록
         * @description 실제 Kubernetes Node API 관측을 저장한 목록입니다. 60초 넘게 관측되지 않으면 STALE, 성공한 전체 관측에서 사라지면 REMOVED입니다. 관측을 설정하지 않은 환경은 빈 목록이며 가짜 노드를 생성하지 않습니다.
         */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        /**
         * 실행 노드 상태·자원·레이블 조회
         * @description nodeId는 Kubernetes UID입니다. CPU/메모리는 Kubernetes quantity 문자열, labels는 관측된 노드 레이블입니다. physical Device와 별개인 실행 호스트를 나타냅니다.
         */
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 소문자 영문으로 시작하는 프로필 키. 영문 소문자·숫자와 구분자 점/밑줄/하이픈을 사용하며 최대 100자입니다.
         * @example temperature-sensor
         */
        ProfileKey: string;
        /**
         * @description MAJOR.MINOR.PATCH 형태의 숫자 버전. 01처럼 앞에 0을 붙이거나 prerelease 문자를 붙일 수 없습니다.
         * @example 1.0.0
         */
        Version: string;
        PublishProfile: {
            key: components["schemas"]["ProfileKey"];
            version: components["schemas"]["Version"];
            /** @description 비어 있지 않은 JSON 규격 문서입니다. 현재 종류별 실행 스키마·외부 참조의 호환성은 검증하지 않습니다. */
            spec: {
                [key: string]: unknown;
            };
        };
        ProfileVersion: {
            /**
             * Format: uuid
             * @description 이 발행 버전의 서버 생성 UUID입니다.
             */
            id: string;
            /**
             * @description 프로필 종류입니다. 종류마다 키·버전 공간이 구분됩니다.
             * @enum {string}
             */
            kind: "DEVICE" | "SERVICE" | "VD";
            key: components["schemas"]["ProfileKey"];
            version: components["schemas"]["Version"];
            /** @description 발행 시 저장된 JSON 규격입니다. */
            spec: {
                [key: string]: unknown;
            };
            /** @description 종류와 정규화된 spec의 SHA-256 식별값. JSON 키 순서나 동등한 숫자 표기는 같은 값이며, spec 또는 종류가 바뀌면 달라집니다. 상세 규칙은 ADR 0002를 따릅니다. */
            digest: string;
            /**
             * Format: date-time
             * @description 최초 발행 시각입니다. 동일 내용 재등록 시 유지됩니다.
             */
            createdAt: string;
        };
        ApiError: {
            /** @enum {string} */
            code: "INVALID_PROFILE" | "PROFILE_CONFLICT" | "PROFILE_NOT_FOUND" | "PROFILE_STORE_UNAVAILABLE" | "PAYLOAD_TOO_LARGE" | "INVALID_DEVICE" | "DEVICE_CONFLICT" | "DEVICE_NOT_FOUND" | "NODE_NOT_FOUND" | "NODE_NOT_READY" | "DEVICE_RELEASED" | "STALE_SESSION" | "OBSERVATION_CONFLICT" | "DEVICE_STORE_UNAVAILABLE";
            message: string;
        };
        /**
         * @example {
         *       "name": "edgeai",
         *       "version": "0.1.0",
         *       "milestone": "M2",
         *       "capabilities": [
         *         "profiles",
         *         "devices",
         *         "nodes"
         *       ]
         *     }
         */
        PlatformInfo: {
            /** @constant */
            name: "edgeai";
            version: string;
            /** @constant */
            milestone: "M2";
            capabilities: string[];
        };
        /**
         * @example {
         *       "status": "UP"
         *     }
         */
        Health: {
            /** @enum {string} */
            status: "UP" | "DOWN" | "OUT_OF_SERVICE" | "UNKNOWN";
        };
        DeviceCreate: {
            key: components["schemas"]["ProfileKey"];
            displayName: string;
            /** Format: uuid */
            profileVersionId: string;
            /** @enum {string} */
            sourceMode: "LIVE" | "REPLAY" | "SYNTHETIC";
        };
        DevicePatch: {
            revision: number;
            displayName: string;
        };
        DeviceAttachmentInput: {
            port: string;
        };
        DeviceSessionInput: {
            /** Format: uuid */
            bootId: string;
        };
        DeviceObservationInput: {
            /** Format: uuid */
            sessionId: string;
            sequence: number;
            /** Format: date-time */
            observedAt: string;
            /** @enum {string} */
            status: "ONLINE" | "OFFLINE";
            attributes: {
                [key: string]: unknown;
            };
        };
        Device: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ProfileKey"];
            displayName: string;
            /** Format: uuid */
            profileVersionId: string;
            /** @enum {string} */
            sourceMode: "LIVE" | "REPLAY" | "SYNTHETIC";
            /** @enum {string} */
            state: "ACTIVE" | "RELEASED";
            revision: number;
            sessionEpoch: number;
            /** @enum {string} */
            connectionStatus: "UNKNOWN" | "ONLINE" | "OFFLINE" | "STALE" | "RELEASED";
            /** Format: date-time */
            lastSeenAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DeviceAttachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: uuid */
            nodeId: string;
            port: string;
            /** Format: date-time */
            attachedAt: string;
            /** Format: date-time */
            detachedAt: string | null;
        };
        DeviceSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: uuid */
            bootId: string;
            epoch: number;
            lastSequence: number;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt: string | null;
        };
        DeviceObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: uuid */
            sessionId: string;
            sequence: number;
            /** Format: date-time */
            observedAt: string;
            /** @enum {string} */
            status: "ONLINE" | "OFFLINE";
            attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            receivedAt: string;
        };
        DeviceDetail: {
            device: components["schemas"]["Device"];
            attachments: components["schemas"]["DeviceAttachment"][];
            sessions: components["schemas"]["DeviceSession"][];
            observations: components["schemas"]["DeviceObservation"][];
        };
        ExecutionNode: {
            /** Format: uuid */
            id: string;
            name: string;
            architecture: string;
            operatingSystem: string;
            /** @enum {string} */
            status: "READY" | "NOT_READY" | "UNKNOWN" | "REMOVED" | "STALE";
            cpu: string;
            memory: string;
            labels: {
                [key: string]: string;
            };
            /** Format: date-time */
            observedAt: string;
        };
        DevicePage: {
            items: components["schemas"]["Device"][];
            nextOffset: number | null;
        };
        NodePage: {
            items: components["schemas"]["ExecutionNode"][];
            nextOffset: number | null;
        };
    };
    responses: {
        /** @description 종류·키·버전·페이지·JSON 형식이 잘못되었습니다. */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_PROFILE",
                 *       "message": "종류, 키, 버전과 JSON 규격을 확인하세요. 규격은 비어 있지 않은 객체여야 합니다."
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 같은 종류·키·버전에 다른 내용이 이미 발행되었습니다. 새 버전을 사용하세요. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PROFILE_CONFLICT",
                 *       "message": "이미 발행한 버전입니다. 내용을 바꾸려면 새 버전을 등록하세요."
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 해당 발행 버전이 없습니다. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PROFILE_NOT_FOUND",
                 *       "message": "해당 Profile 버전을 찾을 수 없습니다."
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description DB 연결 등 저장소 문제로 요청을 처리할 수 없습니다. 복구 후 재시도하세요. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PROFILE_STORE_UNAVAILABLE",
                 *       "message": "Profile 저장소에 연결할 수 없습니다. 잠시 후 다시 시도하세요."
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
        Kind: "DEVICE" | "SERVICE" | "VD";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Implemented platform capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformInfo"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application and database ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Application or database not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send token as X-CSRF-TOKEN with the session cookie and Basic credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: {
                /** @description 프로필 키 정확 일치 필터. 생략하면 선택한 종류의 전체 키를 조회합니다. */
                key?: components["schemas"]["ProfileKey"];
                /** @description 한 페이지의 최대 항목 수. 1~100, 기본 20입니다. */
                limit?: number;
                /** @description 건너뛸 항목 수. 이전 응답의 nextOffset을 넣으면 다음 페이지입니다. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 발행 버전 목록. items가 빈 배열이면 결과가 없으며 nextOffset이 null이면 마지막 페이지입니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProfileVersion"][];
                        nextOffset: number | null;
                    };
                };
            };
            400: components["responses"]["Invalid"];
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    publishProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "key": "temperature-sensor",
                 *       "version": "1.0.0",
                 *       "spec": {
                 *         "protocol": "mqtt",
                 *         "unit": "celsius"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PublishProfile"];
            };
        };
        responses: {
            /** @description 동일 내용의 기존 버전입니다. 중복 생성하지 않고 기존 결과를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileVersion"];
                };
            };
            /** @description 새 버전을 발행했습니다. Location 헤더로 상세 조회할 수 있습니다. */
            201: {
                headers: {
                    /** @description Version lookup path */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileVersion"];
                };
            };
            400: components["responses"]["Invalid"];
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            /** @description 요청 또는 정규화된 규격이 UTF-8 64 KiB를 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getProfileVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description DEVICE: 장치 규격 / SERVICE: 서비스 규격 / VD: 가상 장치 규격. 동일한 key/version이라도 종류가 다르면 별개입니다. */
                kind: components["parameters"]["Kind"];
                /** @description 조회할 프로필의 고유 키입니다. */
                key: components["schemas"]["ProfileKey"];
                /** @description 조회할 정확한 발행 버전입니다. 예: 1.0.0 */
                version: components["schemas"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileVersion"];
                };
            };
            400: components["responses"]["Invalid"];
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 서버 프로세스 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "UP"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 서버 프로세스가 정상 상태가 아님 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description 최대 항목 수 */
                limit?: number;
                /** @description nextOffset을 전달해 다음 페이지를 조회합니다. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePage"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description 새 객체 생성. 기존 객체의 ID는 바뀌지 않습니다. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    releaseDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatch"];
            };
        };
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    attachDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceAttachmentInput"];
            };
        };
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAttachment"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    openDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceSessionInput"];
            };
        };
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSession"];
                };
            };
            /** @description 새 객체 생성. 기존 객체의 ID는 바뀌지 않습니다. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSession"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reportDeviceObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceObservationInput"];
            };
        };
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceObservation"];
                };
            };
            /** @description 새 객체 생성. 기존 객체의 ID는 바뀌지 않습니다. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceObservation"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 토큰·세션 쿠키 누락/불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 현재 상태·버전·세션·sequence 충돌. 상세 조회 후 요청을 확인하세요. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 요청 크기 제한을 초과했습니다. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listNodes: {
        parameters: {
            query?: {
                /** @description 최대 항목 수 */
                limit?: number;
                /** @description nextOffset을 전달해 다음 페이지를 조회합니다. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePage"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 요청 성공. 재전송은 기존 객체를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionNode"];
                };
            };
            /** @description 필드·UUID·페이지·JSON 형식을 확인하세요. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Basic 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 장치·노드·참조 Profile이 없습니다. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description DB 연결 장애. 복구 후 재시도하세요. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
