/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/build-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Image */
        post: operations["build_image_workflow_build_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/save-and-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow Save Push */
        post: operations["workflow_save_push_workflow_save_and_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/status/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Status */
        get: operations["workflow_status_workflow_status__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Workflow Delete */
        delete: operations["workflow_delete_workflow_delete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuildRequest */
        BuildRequest: {
            /** Tag */
            tag: string;
        };
        /** BuildResponse */
        BuildResponse: {
            /** Status */
            status: string;
            /** Image */
            image: string;
            /** Tag */
            tag: string;
            /** Platforms */
            platforms: string[];
        };
        /** DeleteResponse */
        DeleteResponse: {
            argocd: components["schemas"]["StepResult"];
            git: components["schemas"]["StepResult"];
            local: components["schemas"]["StepResult"];
        };
        /** DeploymentResponse */
        DeploymentResponse: {
            local_result: components["schemas"]["StepResult"];
            git_result: components["schemas"]["StepResult"];
            argocd_result: components["schemas"]["StepResult"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationConfig */
        IntegrationConfig: {
            /** Configured */
            configured: boolean;
            /** Missing */
            missing: string[];
            /** Imagerepository */
            imageRepository: string;
            /** Platforms */
            platforms: string[];
            /** Buildconfigured */
            buildConfigured: boolean;
            /** Repository */
            repository: string;
            /** Branch */
            branch: string;
        };
        /** StepResult */
        StepResult: {
            /** Status */
            status: string;
            /** Action */
            action?: string | null;
            /** Path */
            path?: string | null;
            /** Commit */
            commit?: string | null;
            /** Name */
            name?: string | null;
            /** Sync */
            sync?: string | null;
            /** Health */
            health?: string | null;
            /** Revision */
            revision?: string | null;
            /** Operation */
            operation?: string | null;
            /** Deleting */
            deleting?: boolean | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowDeleteRequest */
        WorkflowDeleteRequest: {
            /** Local Directory */
            local_directory: string;
            /**
             * Filename
             * @default deployment.yaml
             */
            filename: string;
            /** Repo Path */
            repo_path: string;
            /** Commit Message */
            commit_message: string;
        };
        /** WorkflowRequest */
        WorkflowRequest: {
            /** Content */
            content: string;
            /** Local Directory */
            local_directory: string;
            /**
             * Filename
             * @default deployment.yaml
             */
            filename: string;
            /**
             * Overwrite Local
             * @default true
             */
            overwrite_local: boolean;
            /** Repo Path */
            repo_path: string;
            /** Commit Message */
            commit_message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationConfig"];
                };
            };
        };
    };
    build_image_workflow_build_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_save_push_workflow_save_and_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_status_workflow_status__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_delete_workflow_delete_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
