apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgeai
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/dsa04156/edgeai-api
    newTag: bootstrap
  - name: ghcr.io/dsa04156/edgeai-dashboard
    newTag: bootstrap
