apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - broker.yaml
configMapGenerator:
  - name: edgeai-mqtt-config-v1
    namespace: edgeai
    files: [mosquitto.conf]
    options:
      disableNameSuffixHash: true
      immutable: true
      labels: {app.kubernetes.io/part-of: edgeai, app.kubernetes.io/managed-by: edgeai-bootstrap}
patches:
  - path: api.yaml
  - path: minio.yaml
