listener 8883 0.0.0.0
allow_anonymous false
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
certfile /bootstrap/tls.crt
keyfile /bootstrap/tls.key
tls_version tlsv1.2
persistence true
persistence_location /mosquitto/data/
autosave_interval 30
max_packet_size 1048576
max_queued_messages 128
max_queued_bytes 16777216
max_inflight_messages 32
connection_messages false
log_dest stderr
