import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";

test("real immutable DAG publication, idempotent Run and dependency cancellation", async ({ page }, testInfo) => {
  const username = process.env.EDGEAI_API_USER, password = process.env.EDGEAI_API_PASSWORD;
  if (!username || !password) throw new Error("Workflow E2E requires the project development environment");
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  const authorization = `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`;
  const token = await (await page.request.get("/api/control-plane/csrf", { headers: { authorization } })).json();
  const headers = { authorization, "X-CSRF-TOKEN": token.token };
  const key = `workflow-browser-${randomUUID()}`;
  const profile = await page.request.post("/api/control-plane/profiles/SERVICE", { headers, data: { key, version: "1.0.0", spec: { source: "synthetic-browser-test" } } });
  expect(profile.status()).toBe(201); const profileId = (await profile.json()).id;
  await page.goto("/workflows");
  expect((await page.request.get("/api/control-plane/workflows")).status()).toBe(401);
  await page.getByLabel("사용자 이름", { exact: true }).fill(username);
  await page.getByLabel("비밀번호", { exact: true }).fill(password);
  await page.getByRole("button", { name: "연결", exact: true }).click();
  await expect(page.getByRole("button", { name: "연결 해제", exact: true })).toBeVisible();
  await page.getByLabel("워크플로 키", { exact: true }).fill(key);
  await page.getByLabel("워크플로 이름", { exact: true }).fill("브라우저 DAG 시험");
  await page.getByRole("button", { name: "워크플로 생성", exact: true }).click();
  await expect(page.getByText("워크플로를 생성했습니다. DAG 버전을 발행하세요.", { exact: true })).toBeVisible();
  const dag = JSON.stringify({ tasks: ["root", "child", "independent"].map(task => ({ key: task, serviceProfileVersionId: profileId, parameters: { serial: "EXACT_INTEGER" } })),
    dependencies: [{ fromTask: "root", toTask: "child", fromPort: "output", toPort: "input", mode: "BATCH" }] }).replaceAll('"EXACT_INTEGER"', "9007199254740993");
  await page.getByRole("textbox", { name: "DAG JSON", exact: true }).fill(dag.replace('"toTask":"child"', '"toTask":"root"'));
  await page.getByRole("button", { name: "DAG 발행", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: /.+/ })).toContainText("DAG");
  await page.getByRole("textbox", { name: "DAG JSON", exact: true }).fill(dag);
  const publish = page.waitForResponse(r => r.request().method() === "POST" && /\/workflows\/[^/]+\/versions$/.test(r.url()));
  await page.getByRole("button", { name: "DAG 발행", exact: true }).click();
  expect((await publish).status()).toBe(201);
  await expect(page.getByText("DAG 버전을 발행했습니다.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("발행된 DAG JSON", { exact: true })).toContainText("9007199254740993");
  await page.getByRole("button", { name: "DAG 발행", exact: true }).click();
  await expect(page.getByText("같은 내용의 DAG 버전이 이미 있습니다.", { exact: true })).toBeVisible();
  await page.getByRole("textbox", { name: "DAG JSON", exact: true }).fill(dag.replaceAll("9007199254740993", "2"));
  await page.getByRole("button", { name: "DAG 발행", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: /.+/ })).toContainText("새 버전으로 발행");

  await page.getByRole("textbox", { name: "실행 매개변수 JSON", exact: true }).fill('{"serial":9007199254740993}');
  const requestKey = await page.getByLabel("실행 요청 키", { exact: true }).inputValue();
  const created = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/api/control-plane/workflow-runs"));
  await page.getByRole("button", { name: "실행 요청 저장", exact: true }).click();
  const response = await created; expect(response.status()).toBe(201);
  expect(response.request().headers()["idempotency-key"]).toBe(requestKey);
  const run = await response.json();
  await expect(page.getByText("실행 요청을 저장했습니다. 작업은 실행 대기 상태입니다.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "실행 요청 저장", exact: true }).click();
  await expect(page.getByText("동일한 실행 요청을 조회했습니다. 새 실행은 만들지 않았습니다.", { exact: true })).toBeVisible();
  const selected = page.getByRole("region", { name: "선택한 실행", exact: true });
  await selected.getByRole("button", { name: "root", exact: true }).click();
  await expect(selected).toContainText("Attempt #1 · epoch 1 · 접수됨");
  await selected.getByRole("button", { name: "child", exact: true }).click();
  await expect(selected).toContainText("선행 작업을 기다리는 중");
  await selected.getByText("실행 매개변수·작업 상세", { exact: true }).click();
  await expect(page.getByLabel("실행 상세 JSON", { exact: true })).toContainText("9007199254740993");
  await page.screenshot({ path: testInfo.outputPath("workflow-pending.png"), fullPage: true });
  await selected.getByRole("button", { name: "root 작업 취소", exact: true }).click();
  await selected.getByRole("button", { name: "취소 확정", exact: true }).click();
  await expect(selected.getByRole("row").filter({ has: page.getByRole("button", { name: "child", exact: true }) })).toContainText("건너뜀");
  await expect(selected.getByRole("row").filter({ has: page.getByRole("button", { name: "independent", exact: true }) })).toContainText("실행 준비");
  await expect(selected.locator(".stage")).toHaveText("실행 대기");
  await selected.getByRole("button", { name: "child", exact: true }).click();
  await expect(selected).toContainText("생성된 실행 시도가 없습니다.");
  await selected.getByRole("button", { name: "실행 취소", exact: true }).click();
  const cancelled = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith(`/workflow-runs/${run.id}/cancel`));
  await selected.getByRole("button", { name: "취소 확정", exact: true }).click();
  expect((await cancelled).status()).toBe(200);
  await expect(selected.locator(".stage")).toHaveText("취소됨");
  await page.getByRole("button", { name: "실행 요청 저장", exact: true }).click();
  await expect(page.getByText("동일한 실행 요청을 조회했습니다. 새 실행은 만들지 않았습니다.", { exact: true })).toBeVisible();
  await expect(selected.locator(".stage")).toHaveText("취소됨");
  const final = await page.request.get(`/api/control-plane/workflow-runs/${run.id}`, { headers });
  expect((await final.json()).tasks.every((t: { state: string }) => ["CANCELLED", "SKIPPED"].includes(t.state))).toBe(true);
  await page.getByRole("textbox", { name: "실행 매개변수 JSON", exact: true }).fill('{"serial":2}');
  await page.getByRole("button", { name: "실행 요청 저장", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: /.+/ })).toContainText("같은 Idempotency-Key에 다른 실행 입력");
  await page.getByRole("button", { name: "새 실행 키 만들기", exact: true }).click();
  expect(await page.getByLabel("실행 요청 키", { exact: true }).inputValue()).not.toBe(requestKey);
  const nextRun = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/api/control-plane/workflow-runs"));
  await page.getByRole("button", { name: "실행 요청 저장", exact: true }).click();
  const nextResponse = await nextRun; expect(nextResponse.status()).toBe(201);
  const nextId = (await nextResponse.json()).id; expect(nextId).not.toBe(run.id);
  await expect(selected.locator(".stage")).toHaveText("실행 대기");
  await selected.getByRole("button", { name: "실행 취소", exact: true }).click();
  await selected.getByRole("button", { name: "취소 확정", exact: true }).click();
  await expect(selected.locator(".stage")).toHaveText("취소됨");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0]);
  await page.screenshot({ path: testInfo.outputPath("workflow-cancelled.png"), fullPage: true });
  await page.getByRole("button", { name: "연결 해제", exact: true }).click();
  await expect(page.getByRole("heading", { name: "실행 이력", exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
